apiVersion: v1
kind: ConfigMap
metadata:
  name: yumrush-configmap 
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/yumrushDB"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
