name: Azure Web App Deployment

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # No need to log into Azure CLI explicitly when using GitHub-hosted runners

    - name: Build and push docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Azure Web App
      run: |
        az webapp config appsettings set \
          --name fooddeliveryapp \
          --resource-group fooddeliveryresource \
          --settings DOCKER_CUSTOM_IMAGE_NAME=milepelivanov02/yumrush:latest \
                     DOCKER_REGISTRY_SERVER_URL=https://index.docker.io \
                     DOCKER_REGISTRY_SERVER_USERNAME=milepelivanov02 \
                     DOCKER_REGISTRY_SERVER_PASSWORD=tosomalerot420
