name: Azure Web App Deployment

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # No need to log into Azure CLI explicitly when using GitHub-hosted runners

    - name: Build and push docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Azure Web App
      run: az webapp config container set \
           --name fooddeliveryapp \
           --resource-group fooddeliveryresource \
           --docker-custom-image-name milepelivanov02/yumrush:latest \
           --docker-registry-server-url https://index.docker.io \
           --enable-app-service-storage false \
           --multicontainer-config-type compose \
           --multicontainer-config-file docker-compose.yml

    # Optional: Trigger a restart to apply changes (if needed)
    - name: Restart Azure Web App
      run: az webapp restart --name fooddeliveryapp --resource-group fooddeliveryresource
