name: Azure Web App Deployment

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log into Azure CLI
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": ${{ secrets.AZURE_CLIENT_ID }},
            "clientSecret": ${{ secrets.AZURE_CLIENT_SECRET }},
            "subscriptionId": ${{ secrets.AZURE_SUBSCRIPTION_ID }},
            "tenantId": ${{ secrets.AZURE_TENANT_ID }}
          }

    - name: Build and push docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Configure Azure Web App Deployment Center
      run: az webapp deployment container config --name fooddeliveryapp --resource-group fooddeliveryresource --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
