name: Azure Web App Deployment

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Upload Docker Compose file to Azure Web App
      run: |
        az webapp config container set --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RG }} \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose.yml

    - name: Restart Azure App Service
      run: |
        az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RG }}
