name: Backend Docker Build and Push

on:
  push:
    paths:
      - '**' 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        run: |
          docker build -t milepelivanov02/yumrush:latest .

      - name: Push Docker image
        run: |
          docker push milepelivanov02/yumrush:latest
